// Auto-generated by tests/generate_golden.cpp - DO NOT EDIT MANUALLY
#pragma once

struct GoldenCalcRoll { float angles[3]; float velocity[3]; float rollangle; float rollspeed; float expected; };
static const GoldenCalcRoll kGoldenCalcRoll[] = {
    {{0.000000f, 90.000000f, 0.000000f}, {100.000000f, 50.000000f, 0.000000f}, 2.000000f, 200.000000f, 1.000000f},
    {{0.000000f, 0.000000f, 0.000000f}, {0.000000f, 0.000000f, 0.000000f}, 2.000000f, 200.000000f, 0.000000f},
    {{10.000000f, 45.000000f, 0.000000f}, {-200.000000f, 150.000000f, 50.000000f}, 2.000000f, 200.000000f, -2.000000f},
    {{0.000000f, 180.000000f, 0.000000f}, {0.000000f, -300.000000f, 0.000000f}, 2.500000f, 150.000000f, -2.500000f},
    {{0.000000f, 270.000000f, 0.000000f}, {50.000000f, -50.000000f, 0.000000f}, 1.500000f, 250.000000f, -0.300000f},
};

struct GoldenDropPunch { float initial[3]; float frametime; float expected[3]; };
static const GoldenDropPunch kGoldenDropPunch[] = {
    {{5.000000f, 3.000000f, 0.000000f}, 0.010000f, {4.889251f, 2.933551f, 0.000000f}},
    {{10.000000f, -5.000000f, 2.000000f}, 0.020000f, {9.723909f, -4.861955f, 1.944782f}},
    {{0.100000f, 0.050000f, 0.000000f}, 0.050000f, {0.000000f, 0.000000f, 0.000000f}},
    {{0.000000f, 0.000000f, 0.000000f}, 0.010000f, {0.000000f, 0.000000f, 0.000000f}},
};

struct GoldenCheckParam { float cmd[3]; float maxspeed; float clientmaxspeed; float expected_cmd[3]; float expected_speed; };
static const GoldenCheckParam kGoldenCheckParam[] = {
    {{500.000000f, 500.000000f, 0.000000f}, 320.000000f, 320.000000f, {226.274170f, 226.274170f, 0.000000f}, 320.000000f},
    {{200.000000f, 100.000000f, 0.000000f}, 320.000000f, 320.000000f, {200.000000f, 100.000000f, 0.000000f}, 223.606796f},
    {{0.000000f, 0.000000f, 0.000000f}, 320.000000f, 320.000000f, {0.000000f, 0.000000f, 0.000000f}, 0.000000f},
    {{400.000000f, 0.000000f, 300.000000f}, 250.000000f, 250.000000f, {200.000000f, 0.000000f, 150.000000f}, 250.000000f},
};

struct GoldenFriction { float vel[3]; float friction; float stopspeed; float frametime; float expected_vel[3]; };
static const GoldenFriction kGoldenFriction[] = {
    {{200.000000f, 100.000000f, 0.000000f}, 4.000000f, 100.000000f, 0.010000f, {192.000000f, 96.000000f, 0.000000f}},
    {{50.000000f, 0.000000f, 0.000000f}, 4.000000f, 100.000000f, 0.010000f, {46.000000f, 0.000000f, 0.000000f}},
    {{0.050000f, 0.000000f, 0.000000f}, 4.000000f, 100.000000f, 0.010000f, {0.050000f, 0.000000f, 0.000000f}},
};

struct GoldenAccel { bool is_air; float vel[3]; float wishdir[3]; float wishspeed; float accel; float frametime; float expected_vel[3]; };
static const GoldenAccel kGoldenAccel[] = {
    {false, {100.000000f, 0.000000f, 0.000000f}, {1.000000f, 0.000000f, 0.000000f}, 320.000000f, 10.000000f, 0.010000f, {132.000000f, 0.000000f, 0.000000f}},
    {false, {320.000000f, 0.000000f, 0.000000f}, {1.000000f, 0.000000f, 0.000000f}, 320.000000f, 10.000000f, 0.010000f, {320.000000f, 0.000000f, 0.000000f}},
    {false, {100.000000f, 0.000000f, 0.000000f}, {0.000000f, 1.000000f, 0.000000f}, 320.000000f, 10.000000f, 0.010000f, {100.000000f, 31.999998f, 0.000000f}},
    {true, {200.000000f, 0.000000f, 0.000000f}, {0.000000f, 1.000000f, 0.000000f}, 320.000000f, 10.000000f, 0.010000f, {200.000000f, 30.000000f, 0.000000f}},
    {true, {0.000000f, 0.000000f, 0.000000f}, {1.000000f, 0.000000f, 0.000000f}, 250.000000f, 10.000000f, 0.010000f, {25.000000f, 0.000000f, 0.000000f}},
};

struct GoldenRadius { float src[3]; float end[3]; float damage; float radius; float expected; };
static const GoldenRadius kGoldenRadius[] = {
    {{0.000000f, 0.000000f, 0.000000f}, {0.000000f, 0.000000f, 0.000000f}, 100.000000f, 250.000000f, 100.000000f},
    {{0.000000f, 0.000000f, 0.000000f}, {125.000000f, 0.000000f, 0.000000f}, 100.000000f, 250.000000f, 50.000000f},
    {{0.000000f, 0.000000f, 0.000000f}, {250.000000f, 0.000000f, 0.000000f}, 100.000000f, 250.000000f, 0.000000f},
    {{0.000000f, 0.000000f, 0.000000f}, {300.000000f, 0.000000f, 0.000000f}, 100.000000f, 250.000000f, 0.000000f},
    {{0.000000f, 0.000000f, 0.000000f}, {50.000000f, 50.000000f, 0.000000f}, 150.000000f, 0.000000f, 150.000000f},
};

struct GoldenHitgroup { int hitgroup; const char* name; float input_damage; float monster_damage; float player_damage; };
static const GoldenHitgroup kGoldenHitgroup[] = {
    {0, "HITGROUP_GENERIC", 40.000000f, 40.000000f, 40.000000f},
    {1, "HITGROUP_HEAD", 40.000000f, 120.000000f, 120.000000f},
    {2, "HITGROUP_CHEST", 40.000000f, 40.000000f, 40.000000f},
    {3, "HITGROUP_STOMACH", 40.000000f, 40.000000f, 40.000000f},
    {4, "HITGROUP_LEFTARM", 40.000000f, 40.000000f, 40.000000f},
    {5, "HITGROUP_RIGHTARM", 40.000000f, 40.000000f, 40.000000f},
    {6, "HITGROUP_LEFTLEG", 40.000000f, 40.000000f, 40.000000f},
    {7, "HITGROUP_RIGHTLEG", 40.000000f, 40.000000f, 40.000000f},
};

struct GoldenArmor { const char* name; float damage; float initial_armor; int damage_type; bool is_multiplayer; float expected_damage; float expected_armor; };
static const GoldenArmor kGoldenArmor[] = {
    {"bullet_standard_absorption", 50.000000f, 100.000000f, 2, false, 10.000000f, 80.000000f},
    {"armor_exhaustion", 100.000000f, 30.000000f, 2, false, 40.000000f, 0.000000f},
    {"fall_damage_unprotected", 50.000000f, 100.000000f, 32, false, 50.000000f, 100.000000f},
    {"drown_damage_unprotected", 50.000000f, 100.000000f, 16384, false, 50.000000f, 100.000000f},
    {"multiplayer_blast_bonus", 100.000000f, 100.000000f, 64, true, 20.000000f, 20.000000f},
};
