name: Cppcheck Static Analysis

on:
  workflow_dispatch:

jobs:
  cppcheck:
    name: Run Cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install cppcheck
        timeout-minutes: 5
        run: |
          sudo apt-get -o Acquire::http::Timeout="15" -o Acquire::https::Timeout="15" -o Acquire::Retries="3" update && \
          sudo apt-get -o Acquire::http::Timeout="15" -o Acquire::https::Timeout="15" -o Acquire::Retries="3" install -y cppcheck

      - name: Run Cppcheck
        run: |
          echo "Running cppcheck on the entire repository..."
          cppcheck --enable=warning,performance,portability --inline-suppr --suppressions-list=.cppcheck-suppressions --error-exitcode=1 -iutils -iexternal -idevtools .
